
// Hard minimum amounts that can be given
frb.amounts.minimums = {
    /* From https://github.com/wikimedia/wikimedia-fundraising-SmashPig/blob/master/PaymentData/ReferenceData/CurrencyRates.php */
    'ADF' : 5.65,
    'ADP' : 143,
    'AED' : 3.67,
    'AFA' : 73,
    'AFN' : 73,
    'ALL' : 109,
    'AMD' : 477,
    'ANG' : 1.79,
    'AOA' : 278,
    'AON' : 278,
    'ATS' : 12,
    'AUD' : 1.39,
    'AWG' : 1.78,
    'AZM' : 8486,
    'AZN' : 1.7,
    'BAM' : 1.69,
    'BBD' : 2,
    'BDT' : 83,
    'BEF' : 35,
    'BGL' : 1.69,
    'BGN' : 1.69,
    'BHD' : 0.38,
    'BIF' : 1748,
    'BMD' : 1,
    'BND' : 1.38,
    'BOB' : 6.8,
    'BRL' : 4.15,
    'BSD' : 1,
    'BTN' : 72,
    'BWP' : 11,
    'BYR' : 21035,
    'BZD' : 1.98,
    'CAD' : 1.32,
    'CDF' : 1573,
    'CHF' : 0.98,
    'CNY' : 6.83,
    'CRC' : 572,
    'CUC' : 1,
    'CUP' : 25,
    'CVE' : 95,
    'CYP' : 0.51,
    'CZK' : 22,
    'DEM' : 1.69,
    'DJF' : 178,
    'DKK' : 6.42,
    'DOP' : 50,
    'DZD' : 118,
    'ECS' : 24094,
    'EEK' : 13,
    'EGP' : 18,
    'ESP' : 143,
    'ETB' : 27,
    'EUR' : 0.87,
    'FIM' : 5.12,
    'FJD' : 2.1,
    'FKP' : 0.78,
    'FRF' : 5.65,
    'GBP' : 0.78,
    'GEL' : 2.52,
    'GHC' : 47467,
    'GHS' : 4.75,
    'GIP' : 0.78,
    'GMD' : 48,
    'GNF' : 8983,
    'GRD' : 294,
    'GTQ' : 7.5,
    'GYD' : 204,
    'HKD' : 7.85,
    'HNL' : 24,
    'HRK' : 6.4,
    'HTG' : 68,
    'HUF' : 282,
    'IDR' : 14966,
    'IEP' : 0.68,
    'ILS' : 3.61,
    'INR' : 108,
    'IQD' : 1178,
    'IRR' : 42000,
    'ISK' : 109,
    'ITL' : 1669,
    'JMD' : 136,
    'JOD' : 0.71,
    'JPY' : 112,
    'KES' : 100,
    'KGS' : 69,
    'KHR' : 4025,
    'KMF' : 424,
    'KPW' : 135,
    'KRW' : 1120,
    'KWD' : 0.31,
    'KYD' : 0.84,
    'KZT' : 369,
    'LAK' : 8393,
    'LBP' : 1508,
    'LKR' : 162,
    'LRD' : 154,
    'LSL' : 15,
    'LTL' : 2.98,
    'LUF' : 35,
    'LVL' : 0.61,
    'LYD' : 1.37,
    'MAD' : 9.39,
    'MDL' : 17,
    'MGA' : 3311,
    'MGF' : 9150,
    'MKD' : 53,
    'MMK' : 1529,
    'MNT' : 2460,
    'MOP' : 8.08,
    'MRO' : 357,
    'MTL' : 0.37,
    'MUR' : 33,
    'MVR' : 15,
    'MWK' : 717,
    'MYR' : 4.15,
    'MZM' : 59754,
    'MZN' : 60,
    'NAD' : 15,
    'NGN' : 359,
    'NIO' : 32,
    'NLG' : 1.9,
    'NOK' : 8.4,
    'NPR' : 114,
    'NZD' : 1.52,
    'OMR' : 0.39,
    'PAB' : 1,
    'PEN' : 3.3,
    'PGK' : 3.26,
    'PHP' : 54,
    'PKR' : 123,
    'PLN' : 3.72,
    'PTE' : 173,
    'PYG' : 5763,
    'QAR' : 3.57,
    'ROL' : 39889,
    'RON' : 3.99,
    'RSD' : 101,
    'RUB' : 68,
    'RWF' : 862,
    'SAR' : 3.75,
    'SBD' : 7.6,
    'SCR' : 13,
    'SDD' : 1795,
    'SDG' : 18,
    'SDP' : 2261,
    'SEK' : 9.08,
    'SGD' : 1.38,
    'SHP' : 0.78,
    'SIT' : 207,
    'SKK' : 26,
    'SLL' : 8430,
    'SOS' : 542,
    'SRD' : 7.41,
    'SRG' : 7408,
    'STD' : 21070,
    'SVC' : 8.75,
    'SYP' : 215,
    'SZL' : 15,
    'THB' : 33,
    'TJS' : 9.36,
    'TMM' : 17050,
    'TMT' : 3.41,
    'TND' : 2.76,
    'TOP' : 2.29,
    'TRL' : 6629223,
    'TRY' : 6.63,
    'TTD' : 6.64,
    'TWD' : 31,
    'TZS' : 2281,
    'UAH' : 28,
    'UGX' : 3749,
    'USD' : 1,
    'UZS' : 7780,
    'VEB' : 6050841136,
    'VEF' : 6050841,
    'VND' : 23150,
    'VUV' : 111,
    'WST' : 2.64,
    'XAF' : 565,
    'XCD' : 2.7,
    'XOF' : 565,
    'XPF' : 103,
    'YER' : 250,
    'YUN' : 101,
    'ZAR' : 15,
    'ZMK' : 5176,
    'ZWD' : 373,
    /* Astropay currencies have higher minimums - 1.50 USD */
    'ARS' : 58.5,
    'BRL' : 6.23,
    'CLP' : 1035,
    'COP' : 4640,
    'MXN' : 28.5
};

frb.amounts.options7 = {
    // Big English
    'USD' : [2.75, 5, 10, 20, 30, 50, 100],
    'CAD' : [2.75, 5, 10, 20, 30, 50, 100],
    'AUD' : [2.75, 5, 10, 20, 30, 50, 100],
    'NZD' : [2.75, 5, 10, 20, 30, 50, 100],
    'GBP' : [2, 5, 10, 20, 30, 50, 100],
    'EUR' : {
        'default' : [2, 5, 10, 20, 30, 50, 100]
    },
    // Others
    'DKK' : [20, 100, 150, 200, 300, 500, 1000],
    'HUF' : [500, 1000, 2000, 4000, 5000, 7000, 10000],
    'ILS' : [10, 50, 100, 200, 300, 500, 1000],
    'INR' : [150, 300, 500, 1000, 1500, 3000, 5000],
    'JPY' : [300, 1000, 1500, 2000, 3000, 5000, 10000],
    'MYR' : [10, 30, 50, 100, 200, 300, 500],
    'NOK' : [20, 100, 150, 200, 500, 750, 1000],
    'PLN' : [10, 20, 50, 100, 200, 300, 500],
    'RON' : [10, 50, 75, 100, 200, 300, 500],
    'SEK' : [30, 50, 100, 200, 300, 500, 1000],
    'UAH' : [50, 75, 150, 300, 500, 750, 1000],
    'ZAR' : [30, 50, 100, 200, 300, 500, 1000],
    // Latin America
    'BRL' : [10, 20, 30, 50, 100, 250, 500],
    'ARS' : [60, 100, 200, 400, 1000, 1500, 2000],
    'CLP' : [1500, 2500, 5000, 10000, 15000, 25000, 50000],
    'COP' : [7000, 10000, 20000, 50000, 100000, 150000, 200000],
    'MXN' : [35, 50, 100, 200, 500, 750, 1000],
    'PEN' : [10, 30, 50, 150, 200, 275, 700],
    'UYU' : [70, 100, 200, 400, 1000, 1500, 2000]
};

// 5 amount options. Used e.g. on mobile
// Usual formula: take 1st, 3rd, 4th, 6th and 7th from asks7 */
frb.amounts.options5 = {
    // Big English
    'USD' : [2.75, 16.36, 20, 50, 100],
    'CAD' : [2.75, 15, 20, 50, 100],
    'AUD' : [2.75, 15, 20, 50, 100],
    'NZD' : [2.75, 15, 20, 50, 100],
    'GBP' : [2, 10, 20, 50, 100],
    'EUR' : [2, 10, 20, 50, 100],
    // Others
    'DKK' : [20, 100, 200, 500, 1000],
    'HUF' : [500, 2500, 4000, 7000, 10000],
    'ILS' : [10, 50, 200, 600, 1000],
    'INR' : [150, 500, 1000, 3000, 5000],
    'JPY' : [300, 1500, 2000, 5000, 10000],
    'MYR' : [10, 50, 100, 300, 500],
    'NOK' : [20, 100, 200, 500, 1000],
    'PLN' : [10, 50, 100, 300, 500],
    'RON' : [10, 50, 100, 200, 1000],
    'SEK' : [30, 100, 200, 500, 1000],
    'UAH' : [50, 150, 300, 750, 1000],
    'ZAR' : [30, 100, 200, 500, 1000],
    // Latin America
    'BRL' : [10, 30, 50, 100, 250],
    'ARS' : [60, 200, 400, 1000, 2000],
    'CLP' : [1500, 5000, 10000, 25000, 50000],
    'COP' : [7000, 20000, 50000, 150000, 200000],
    'MXN' : [35, 100, 200, 750, 1000],
    'PEN' : [10, 50, 150, 300, 700],
    'UYU' : [70, 200, 400, 1500, 2000]
};

/* "Average" donation */
frb.amounts.averages = {
    'USD' : 16.36,
    'CAD' : 15,
    'AUD' : 15,
    'NZD' : 15,
    'GBP' : 10,
    'EUR' : 10,
    // Others
    'DKK' : 100,
    'HUF' : 2500,
    'ILS' : 50,
    'INR' : 1000,
    'JPY' : 1500,
    'MYR' : 50,
    'NOK' : 100,
    'PLN' : 50,
    'RON' : 50,
    'SEK' : 100,
    'UAH' : 150,
    'ZAR' : 150,
    // Latin America
    'BRL' : 25,
    'ARS' : 200,
    'CLP' : 8000,
    'COP' : 30000,
    'MXN' : 150,
    'PEN' : 40,
    'UYU' : 300
};

// 'If everyone gave X'. Mostly the same as first asks option.
frb.amounts.ifEveryone = {
    // Big English
    'USD' : 2.75,
    'CAD' : 2.75,
    'AUD' : 2.75,
    'NZD' : 2.75,
    'GBP' : 2,
    'EUR' : {
        'default' : 2
    },
    // Others
    'DKK' : 20,
    'HUF' : 500,
    'ILS' : 10,
    'INR' : 150,
    'JPY' : 300,
    'MYR' : 10,
    'NOK' : 20,
    'PLN' : 10,
    'RON' : 10,
    'SEK' : 30,
    'UAH' : 50,
    'ZAR' : 30,
    // Latin America
    'BRL' : 10,
    'ARS' : 60,
    'CLP' : 1500,
    'COP' : 7000,
    'MXN' : 35,
    'PEN' : 10,
    'UYU' : 70
};

// Minimum fee/PTF amounts. Default is 0.35.
// Updated 2018-07-05 based on Ppena's feedback
// Updated 2019-05-21 to approx 0.35 USD equivalent
frb.amounts.feeMinimums = {
    'DKK' : 2,
    'HUF' : 100,
    'ILS' : 1.2,
    'INR' : 25,
    'JPY' : 35,
    'MYR' : 1,
    'NOK' : 3,
    'PLN' : 1.35,
    'RON' : 1.5,
    'SEK' : 3,
    'UAH' : 10,
    'ZAR' : 5,
    // Latin America
    'BRL' : 1.5,
    'ARS' : 15,
    'CLP' : 250,
    'COP' : 1000,
    'PEN' : 1.2,
    'MXN' : 6,
    'UYU' : 12
};

// If one-time amount <= left amount, suggest right amount for monthly
frb.amounts.monthlySuggest = {
    'USD' : [ // also CAD, AUD, NZD
        [ 2.74, 0 ],
        [ 9, 1.75 ],
        [ 12, 2 ],
        [ 15, 2.5 ],
        [ 18, 3 ],
        [ 21, 3.5 ],
        [ 24, 4 ],
        [ 27, 4.5 ],
        [ 30, 5 ],
        [ 33, 5.5 ],
        [ 36, 6 ],
        [ 39, 6.5 ],
        [ 42, 7 ],
        [ 45, 7.5 ],
        [ 48, 8 ],
        [ 51, 8.5 ],
        [ 54, 9 ],
        [ 57, 9.5 ],
        [ 60, 10 ],
        [ 63, 10.5 ],
        [ 66, 11 ],
        [ 69, 11.5 ],
        [ 72, 12 ],
        [ 75, 12.5 ],
        [ 102, 17 ],
        [ 250, 25 ],
        [ 480, 50 ],
        [ Infinity, 0 ]
    ],
    'GBP' : [ // also EUR
        [ 1.99, 0 ],
        [ 9, 1.75 ],
        [ 12, 2 ],
        [ 15, 2.5 ],
        [ 18, 3 ],
        [ 21, 3.5 ],
        [ 24, 4 ],
        [ 27, 4.5 ],
        [ 30, 5 ],
        [ 33, 5.5 ],
        [ 36, 6 ],
        [ 39, 6.5 ],
        [ 42, 7 ],
        [ 45, 7.5 ],
        [ 48, 8 ],
        [ 51, 8.5 ],
        [ 54, 9 ],
        [ 57, 9.5 ],
        [ 60, 10 ],
        [ 63, 10.5 ],
        [ 66, 11 ],
        [ 69, 11.5 ],
        [ 72, 12 ],
        [ 75, 12.5 ],
        [ 102, 17 ],
        [ 250, 25 ],
        [ 480, 50 ],
        [ Infinity, 0 ]
    ],
    'INR' : [ 
        [ 300, 150 ],
        [ 500, 175 ],
        [ 1000, 250 ],
        [ 1500, 350 ],
        [ 3000, 500 ],
        [ 5000, 750 ],
        [ 10000, 1000 ],
        [ 25000, 2500 ],
        [ Infinity, 5000 ]
    ],
    'JPY' : [
        [ 1000, 300 ],
        [ 1500, 450 ],
        [ 2000, 500 ],
        [ 3000, 700 ],
        [ 5000, 900 ],
        [ 10000, 1100 ],
        [ 25000, 2500],
        [ 50000, 5000],
        [ 100000, 12000],
        [ 250000, 25000],
        [ 500000, 50000],        
        [ 750000, 75000],  
        [ Infinity, 100000]
    ],
    'SEK' : [ 
        [ 50, 25 ],
        [ 100, 30 ],
        [ 200, 50 ],
        [ 300, 70 ],
        [ 500, 90 ],
        [ 1000, 110 ],
        [ 2500, 250 ],
        [ 5000, 500 ],
        [ Infinity, 1000 ]
    ]
};
frb.amounts.monthlySuggest.EUR = frb.amounts.monthlySuggest.GBP;
frb.amounts.monthlySuggest.CAD = frb.amounts.monthlySuggest.USD;
frb.amounts.monthlySuggest.AUD = frb.amounts.monthlySuggest.USD;
frb.amounts.monthlySuggest.NZD = frb.amounts.monthlySuggest.USD;

frb.currencyFormats = {
    'USD' : '$\t',
    'CAD' : {
        'fr' : '$\t',
        'default' : '$\t'
    },
    'AUD' : '$\t',
    'NZD' : '$\t',
    'GBP' : '£\t',
    'EUR' : {
        'en' : '€\t',
        'cy' : '€\t',
        'ga' : '€\t',
        'mt' : '€\t',
        'nl' : '€ \t',
        'lv' : '€ \t',
        'tr' : '€ \t',
        'default' : '\t €'
    },
    // Others
    'DKK' : '\t kr.',
    'HUF' : '\t Ft',
    'ILS' : {
        'he' : '\t ₪',
        'yi' : '\t ₪',
        'ar' : '\t ₪',
        'default' : '₪ \t'
    },
    'INR' : '₹\t',
    'JPY' : '¥\t',
    'MYR' : 'RM\t',
    'NOK' : '\t kr',
    'PLN' : '\t zł',
    'RON' : '\t lei',
    'SEK' : '\t kr',
    'UAH' : '₴\t',
    'ZAR' : 'R \t',
    // Latin America
    'BRL' : 'R$\t',
    'ARS' : '$\t',
    'CLP' : '$\t',
    'COP' : '$\t',
    'MXN' : '$\t',
    'PEN' : 'S/. \t',
    'UYU' : '$U \t'
};

// Check in user language first, then fall back to English
frb.countryNames = {
    'en' : {
        'US' : 'the U.S.',
        'CA' : 'Canada',
        'GB' : 'the UK',
        'IE' : 'Ireland',
        'AU' : 'Australia',
        'NZ' : 'New Zealand',
        'AR' : 'Argentina',
        'AT' : 'Austria',
        'BE' : 'Belgium',
        'BR' : 'Brazil',
        'CL' : 'Chile',
        'CO' : 'Colombia',
        'DK' : 'Denmark',
        'ES' : 'Spain',
        'FR' : 'France',
        'HK' : 'Hong Kong',
        'HU' : 'Hungary',
        'IL' : 'Israel',
        'IN' : 'India',
        'IT' : 'Italy',
        'JP' : 'Japan',
        'LU' : 'Luxembourg',
        'LV' : 'Latvia',
        'MX' : 'Mexico',
        'MY' : 'Malaysia',
        'NL' : 'the Netherlands',
        'NO' : 'Norway',
        'PE' : 'Peru',
        'PL' : 'Poland',
        'PT' : 'Portugal',
        'RO' : 'Romania',
        'SE' : 'Sweden',
        'SK' : 'Slovakia',
        'UA' : 'Ukraine',
        'UY' : 'Uruguay',
        'ZA' : 'South Africa'
    },
    'es' : {
        'MX' : 'México',
        'PE' : 'Perú',
        'ES' : 'España'
    },
    'da' : {
        'AT' : 'i Østrig',
        'BE' : 'i Belgien',
        'DK' : 'i Danmark',
        'HU' : 'i Ungarn',
        'IL' : 'i Israel',
        'LV' : 'i Letland',
        'LU' : 'i Luxembourg',
        'MY' : 'i Malaysia',
        'NO' : 'i Norge',
        'PL' : 'i Polen',
        'PT' : 'i Portugal',
        'RO' : 'i Rumænien',
        'SK' : 'i Slovakiet',
        'ZA' : 'i Sydafrika',
        'UA' : 'i Ukraine'
    },
    'nl' : {
        'NL' : 'in Nederland',
        'AT' : 'in Oostenrijk',
        'BE' : 'in België',
        'DK' : 'in Denemarken',
        'HU' : 'in Hongarije',
        'IL' : 'in Israël',
        'LV' : 'in Letland',
        'LU' : 'in Luxemburg',
        'MY' : 'in Maleisië',
        'NO' : 'in Noorwegen',
        'PL' : 'in Polen',
        'PT' : 'in Portugal',
        'RO' : 'in Roemenië',
        'SK' : 'in Slowakije',
        'ZA' : 'in Zuid-Afrika',
        'UA' : 'in Oekraïne'
    },
    'fr' : {
        'AT' : 'en Autriche',
        'BE' : 'en Belgique',
        'DK' : 'au Danemark',
        'HU' : 'en Hongrie',
        'IL' : 'en Israël',
        'LV' : 'en Lettonie',
        'LU' : 'au Luxembourg',
        'MY' : 'en Malaisie',
        'NO' : 'en Norvège',
        'PL' : 'en Pologne',
        'PT' : 'au Portugal',
        'RO' : 'en Roumanie',
        'SK' : 'en Slovaquie',
        'ZA' : 'en Afrique du Sud',
        'UA' : 'en Ukraine'
    },
    'de' : {
        'AT' : 'in Österreich',
        'BE' : 'in Belgien',
        'DK' : 'in Dänemark',
        'HU' : 'in Ungarn',
        'IL' : 'in Israel',
        'LV' : 'in Lettland',
        'LU' : 'in Luxemburg',
        'MY' : 'in Malaysia',
        'NO' : 'in Norwegen',
        'PL' : 'in Polen',
        'PT' : 'in Portugal',
        'RO' : 'in Rumänien',
        'SK' : 'in der Slowakei',
        'ZA' : 'in Südafrika',
        'UA' : 'in der Ukraine'
    },
    'he' : {
        'AT' : 'באוסטרליה',
        'BE' : 'בבלגיה',
        'DK' : 'בדנמרק',
        'HU' : 'בהונגריה',
        'IL' : 'בישראל',
        'LV' : 'בלטביה',
        'LU' : 'בלוקסמבורג',
        'MY' : 'במלזיה',
        'NO' : 'בנורבגיה',
        'PL' : 'בפולין',
        'PT' : 'בפורטוגל',
        'RO' : 'ברומניה',
        'SK' : 'בסלובקיה',
        'ZA' : 'בדרום אפריקה',
        'UA' : 'באוקראינה'
    },
    'hu' : {
        'AT' : 'Ausztriában',
        'BE' : 'Belgiumban',
        'DK' : 'Dániában',
        'HU' : 'magyarországi',
        'IL' : 'Izraelben',
        'LV' : 'Lettországban',
        'LU' : 'Luxemburgban',
        'MY' : 'Malajziában',
        'NO' : 'Norvégiában',
        'PL' : 'Lengyelországban',
        'PT' : 'Portugáliában',
        'RO' : 'Romániában',
        'SK' : 'Szlovákiában',
        'ZA' : 'Dél-Afrikában',
        'UA' : 'Ukrajnában'
    },
    'lv' : {
        'AT' : 'valstī Austrijā',
        'BE' : 'valstī Beļģijā',
        'DK' : 'valstī Dānijā',
        'HU' : 'valstī Ungārijā',
        'IL' : 'Izraēlas valstī',
        'LV' : 'valstī Latvijā',
        'LU' : 'valstī Luksemburgā',
        'MY' : 'valstī Malaizijā',
        'NO' : 'valstī Norvēģijā',
        'PL' : 'valstī Polijā',
        'PT' : 'valstī Portugālē',
        'RO' : 'valstī Rumānijā',
        'SK' : 'valstī Slovākijā',
        'ZA' : 'Dienvidāfrikas valstī',
        'UA' : 'valstī Ukrainā'
    },
    'nb' : {
        'AT' : 'i Østerrike',
        'BE' : 'i Belgia',
        'DK' : 'i Danmark',
        'HU' : 'i Ungarn',
        'IL' : 'i Israel',
        'LV' : 'i Latvia',
        'LU' : 'i Luxembourg',
        'MY' : 'i Malaysia',
        'NO' : 'i Norge',
        'PL' : 'i Polen',
        'PT' : 'i Portugal',
        'RO' : 'i Romania',
        'SK' : 'i Slovakia',
        'ZA' : 'i Sør-Afrika',
        'UA' : 'i Ukraina'
    },
    'pl' : {
        'AT' : 'w Austrii',
        'BE' : 'w Belgii',
        'DK' : 'w Danii',
        'HU' : 'na Węgrzech',
        'IL' : 'w Izraelu',
        'LV' : 'na Łotwie',
        'LU' : 'w Luksemburgu',
        'MY' : 'w Malezji',
        'NO' : 'w Norwegii',
        'PL' : 'w Polsce',
        'PT' : 'w Portugalii',
        'RO' : 'w Rumunii',
        'SK' : 'na Słowacji',
        'ZA' : 'w Republice Południowej Afryki',
        'UA' : 'na Ukrainie'
    },
    'pt' : {
        'AT' : 'na Áustria',
        'BE' : 'na Bélgica',
        'DK' : 'na Dinamarca',
        'HU' : 'na Hungria',
        'IL' : 'em Israel',
        'LV' : 'na Letónia',
        'LU' : 'no Luxemburgo',
        'MY' : 'na Malásia',
        'NO' : 'na Noruega',
        'PL' : 'na Polónia',
        'PT' : 'em Portugal',
        'RO' : 'na Roménia',
        'SK' : 'na Eslováquia',
        'ZA' : 'na África do Sul',
        'UA' : 'na Ucrânia'
    },
    'ro' : {
        'AT' : 'în Austria',
        'BE' : 'în Belgia',
        'DK' : 'în Danemarca',
        'HU' : 'în Ungaria',
        'IL' : 'în Israel',
        'LV' : 'în Latvia',
        'LU' : 'în Luxemburg',
        'MY' : 'în Malaezia',
        'NO' : 'în Norvegia',
        'PL' : 'în Polonia',
        'PT' : 'în Portugalia',
        'RO' : 'în România',
        'SK' : 'în Slovacia',
        'ZA' : 'în Africa de Sud',
        'UA' : 'în Ucraina'
    },
    'ru' : {
        'AT' : 'в Австрии',
        'BE' : 'в Бельгии',
        'DK' : 'в Дании',
        'HU' : 'в Венгрии',
        'IL' : 'в Израиле',
        'LV' : 'в Латвии',
        'LU' : 'в Люксембурге',
        'MY' : 'в Малайзии',
        'NO' : 'в Норвегии',
        'PL' : 'в Польше',
        'PT' : 'в Португалии',
        'RO' : 'в Румынии',
        'SK' : 'в Словакии',
        'ZA' : 'в Южной Африке',
        'UA' : 'в Украине'
    },
    'sk' : {
        'AT' : 'v Rakúsku',
        'BE' : 'v Belgicku',
        'DK' : 'v Dánsku',
        'HU' : 'v Maďarsku',
        'IL' : 'v Izraeli',
        'LV' : 'v Lotyšsku',
        'LU' : 'v Luxembursku',
        'MY' : 'v Malajzii',
        'NO' : 'v Nórsku',
        'PL' : 'v Poľsku',
        'PT' : 'v Portugalsku',
        'RO' : 'v Rumunsku',
        'SK' : 'na Slovensku',
        'ZA' : 'v Juhoafrickej republike',
        'UA' : 'na Ukrajine'
    },
    'uk' : {
        'AT' : 'у Австрії',
        'BE' : 'у Бельгії',
        'DK' : 'у Данії',
        'HU' : 'в Угорщині',
        'IL' : 'в Ізраїлі',
        'LV' : 'у Латвії',
        'LU' : 'у Люксембургу',
        'MY' : 'у Малайзії',
        'NO' : 'у Норвегії',
        'PL' : 'у Польщі',
        'PT' : 'у Португалії',
        'RO' : 'у Румунії',
        'SK' : 'у Словаччині',
        'ZA' : 'у ПАР',
        'UA' : 'в Україні'
    }
};

frb.dayNames = {
    'en' : [ 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday' ],
    'ja' : [ '日', '月', '火', '水', '木', '金', '土' ],
    'es' : [ 'domingo', 'lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado' ],
    'sv' : [ 'söndag', 'måndag', 'tisdag', 'onsdag', 'torsdag', 'fredag', 'lördag' ],
    'da' : [ 'søndag', 'mandag', 'tirsdag', 'onsdag', 'torsdag', 'fredag', 'lørdag' ],
    'nb' : [ 'søndag', 'mandag', 'tirsdag', 'onsdag', 'torsdag', 'fredag', 'lørdag' ],
    'it' : [ 'domenica', 'lunedì', 'martedì', 'mercoledì', 'giovedì', 'venerdì', 'sabato' ],
    'nl' : [ 'zondag', 'maandag', 'dinsdag', 'woensdag', 'donderdag', 'vrijdag', 'zaterdag' ],
    'fr' : [ 'dimanche', 'lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi' ],
    'de' : [ 'Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag' ],
    'he' : [ 'ראשון', 'שני', 'שלישי', 'רביעי', 'חמישי', 'שישי', 'שבת' ],
    'lv' : [ 'svētdienā', 'pirmdienā', 'otrdienā', 'trešdienā', 'ceturtdienā', 'piektdienā', 'sestdienā' ],
    'pl' : [ 'niedzielę', 'poniedziałek', 'wtorek', 'środę', 'czwartek', 'piątek', 'sobotę' ],
    'ru' : [ 'воскресенье', 'понедельник', 'вторник', 'среду', 'четверг', 'пятницу', 'субботу' ],
    'uk' : [ 'неділі', 'понеділка', 'вівторка', 'середи', 'четверга', 'п’ятниц', 'суботи' ],
    'hu' : [ 'vasárnapon', 'hétfőn', 'kedden', 'szerdán', 'csütörtökön', 'pénteken', 'szombaton' ],
    'ro' : [ 'duminica', 'lunea', 'marțea', 'miercurea', 'joia', 'vinerea', 'sâmbăta' ]
};

// "This fooday" translations. Needed for some languages where gender varies and "this" must agree
frb.dayNamesThis = {
    'en' : [ 'this Sunday', 'this Monday', 'this Tuesday', 'this Wednesday', 'this Thursday', 'this Friday', 'this Saturday' ],
    'jp' : [ 'この日曜日', 'この月曜日', 'この火曜日', 'この水曜日', 'この木曜日', 'この金曜日', 'この土曜日' ],
    'it' : [ 'questa domenica', 'questo lunedì', 'questo martedì', 'questo mercoledì', 'questo giovedì', 'questo venerdì', 'questo sabato'],
    'pl' : [ 'w tę niedzielę', 'w ten poniedziałek', 'w ten wtorek', 'w tę środę', 'w ten czwartek', 'w ten piątek', 'w tę sobotę' ],
    'ru' : [ 'в это воскресенье', 'в этот понедельник', 'в этот вторник', 'в эту среду', 'в этот четверг', 'в эту пятницу', 'в эту субботу' ],
    'uk' : [ 'цієї неділі', 'цього понеділка', 'цього вівторка', 'цієї середи', 'цього четверга', 'цієї п’ятниці', 'цієї суботи' ],
    'pt' : [ 'neste domingo', 'nesta segunda-feira', 'nesta terça-feira', 'nesta quarta-feira', 'nesta quinta-feira', 'nesta sexta-feira', 'neste sábado'],
    'sk' : [ 'túto nedeľu', 'tento pondelok', 'tento utorok', 'túto stredu', 'tento štvrtok', 'tento piatok', 'túto sobotu']
};

frb.iPadTranslations = {
    'en' : 'iPad'
};